# Generated by Django 3.1.6 on 2021-07-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='bank_model',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
