# Generated by Django 3.1.6 on 2021-07-04 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_auto_20210704_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_model',
            name='account_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
    ]
