# Generated by Django 3.1.6 on 2021-07-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_bank_model_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.CharField(max_length=100)),
                ('receive', models.CharField(max_length=100)),
                ('amount', models.FloatField(max_length=40)),
                ('dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
