# Generated by Django 3.1.6 on 2021-07-04 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_transaction_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_model',
            name='dt',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
